_core:
  default_config_hash: 8_qX6deS-sD3xX39HCLpemQQ6C7YuiKujIdB3qH7cZI
favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: 'public://logo-black.png'
  use_default: false
all_icons_show: 0
facebook_url: ''
twitter_url: ''
instagram_url: ''
linkedin_url: ''
youtube_url: ''
vimeo_url: ''
telegram_url: ''
whatsapp_url: ''
github_url: ''
vk_url: ''
slider_show: 0
slider_code: ''
slider_image:
  - '1'
slider_image_path: ''
front_sidebar: 0
google_font: local
bootstrapicons: 0
comment_user_pic: 1
node_author_pic: 0
node_tags: 0
font_icon_fontawesome: 0
font_icon_material: 0
copyright_text: 1
scrolltotop_on: 1
styling: 0
styling_code: ''
font_icon_fontawesome5: 0
font_icon_fontawesome6: 0
